STKAttributeError
=================

.. py:class:: ansys.stk.core.utilities.exceptions.STKAttributeError

   AttributeError

   Raised when attempting to set an unrecognized attribute within the STK API.

.. py:currentmodule:: STKAttributeError


Import detail
-------------

.. code-block:: python

    from ansys.stk.core.utilities.exceptions import STKAttributeError


